global:
  scrape_interval: 15s                      # Adjust the scrape interval as needed

  scrape_configs:
    - job_name: 'traefik'
      metrics_path: '/metrics'
      static_configs:
         - targets: ['traefik:8080']            